image: gcc

before_script:
  - apt-get update -qq
  - apt-get install -y -qq make gcc flex bison autoconf automake pkg-config libtool libtool-bin m4
 
stages:
  - build

build:
  stage: build
  script:
    - ./autogen.sh
    - make
    - make check
