default:
  image: ubuntu:latest

before_script:
  - apt-get update -qq
  - apt-get install -y -qq autoconf automake pkg-config libtool m4
 
stages:
  - build
  - test

build:
  stage: build
  script:
    - ./autogen.sh
    - make

test:
  stage: test
  script:
    - make check
